#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-grizzled-scala_2.12
Version  : 4.2.0
Release  : 2
URL      : https://github.com/bmc/grizzled-scala/archive/release-4.2.0.tar.gz
Source0  : https://github.com/bmc/grizzled-scala/archive/release-4.2.0.tar.gz
Source1  : https://repo1.maven.org/maven2/org/clapper/grizzled-scala_2.12/4.2.0/grizzled-scala_2.12-4.2.0.jar
Source2  : https://repo1.maven.org/maven2/org/clapper/grizzled-scala_2.12/4.2.0/grizzled-scala_2.12-4.2.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-grizzled-scala_2.12-data = %{version}-%{release}

%description
# Grizzled Scala: A general-purpose library of Scala classes and objects
[![Build Status](https://travis-ci.org/bmc/grizzled-scala.svg?branch=master)](https://travis-ci.org/bmc/grizzled-scala)
[![Maven Central](https://maven-badges.herokuapp.com/maven-central/org.clapper/grizzled-scala_2.11/badge.svg)](https://maven-badges.herokuapp.com/maven-central/org.clapper/grizzled-scala_2.11)

%package data
Summary: data components for the mvn-grizzled-scala_2.12 package.
Group: Data

%description data
data components for the mvn-grizzled-scala_2.12 package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/clapper/grizzled-scala_2.12/4.2.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/clapper/grizzled-scala_2.12/4.2.0/grizzled-scala_2.12-4.2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/clapper/grizzled-scala_2.12/4.2.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/clapper/grizzled-scala_2.12/4.2.0/grizzled-scala_2.12-4.2.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/clapper/grizzled-scala_2.12/4.2.0/grizzled-scala_2.12-4.2.0.jar
/usr/share/java/.m2/repository/org/clapper/grizzled-scala_2.12/4.2.0/grizzled-scala_2.12-4.2.0.pom
